// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filters/BitmapFilterType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.filters
{
    
    
    public final class BitmapFilterType
    {
        // Defines the setting that applies a filter to the entire area of an object.
        public static const FULL:String = "full";
        
        // Defines the setting that applies a filter to the inner area of an object.
        public static const INNER:String = "inner";
        
        // Defines the setting that applies a filter to the outer area of an object.
        public static const OUTER:String = "outer";
        
        
    }
}