// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/filters/DisplacementMapFilterMode.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.filters
{
    
    
    public final class DisplacementMapFilterMode
    {
        // Clamps the displacement value to the edge of the source image.
        public static const CLAMP:String = "clamp";
        
        // If the displacement value is outside the image, substitutes the values in the color and alpha properties.
        public static const COLOR:String = "color";
        
        // If the displacement value is out of range, ignores the displacement and uses the source pixel.
        public static const IGNORE:String = "ignore";
        
        // Wraps the displacement value to the other side of the source image.
        public static const WRAP:String = "wrap";
        
        
    }
}
