// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/LocaleID.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{
    
    
    public final class LocaleID
    {
        // [static] Indicates that the user's default linguistic preferences should be used, as specified in the user's operating system settings.
        public static const DEFAULT:String = "i-default";
        

        // [read-only] Returns a slightly more "canonical" locale identifier.
        private var _name: String;
        
        // [read-only] The status of the most recent operation that this LocaleID object performed.
        private var _lastOperationStatus: String;
        

        
        public function LocaleID(name:String)
        {
            super();
            this._name = name;
        }
        
        
        

        // [static] Returns a list of acceptable locales based on a list of desired locales and a list of the locales that are currently available.
        public static function determinePreferredLocales(want:Vector.<String>, have:Vector.<String>, keyword:String = "userinterface"):Vector.<String>
        {
            // Unknown Implementation
        }

        // Returns an object containing all of the key and value pairs from the LocaleID object.
        public function getKeysAndValues():Object
        {
            // Unknown Implementation
        }

        // Returns the language code specified by the locale ID name.
        public function getLanguage():String
        {
            // Unknown Implementation
        }

        // Returns the region code specified by the locale ID name.
        public function getRegion():String
        {
            // Unknown Implementation
        }

        // Returns the script code specified by the locale ID name.
        public function getScript():String
        {
            // Unknown Implementation
        }

        // Returns the language variant code specified by the locale ID name.
        public function getVariant():String
        {
            // Unknown Implementation
        }

        // Specifies whtehr the text direction for the specified locale is right to left.
        public function isRightToLeft():Boolean
        {
            // Unknown Implementation
        }

        public function get name() : String
        {
            return this._name;
        }
        

        public function get lastOperationStatus() : String
        {
            return this._lastOperationStatus;
        }
        
    }
}