// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/globalization/NumberParseResult.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.globalization
{
    
    
    public final class NumberParseResult
    {
        

        // The value of the numeric portion of the input string.
        private var _value: Number;
        
        // The index of the first character of the numeric portion of the input string.
        private var _startIndex: int;
        
        // The index of the character after the last character of the numeric portion of the input string.
        private var _endIndex: int;
        

        
        public function NumberParseResult(value:Number = NaN, startIndex:int = 0x7fffffff, endIndex:int = 0x7fffffff)
        {
            this._value = value;
            this._startIndex = startIndex;
            this._endIndex = endIndex;
        }
        
        
        

        public function get value() : Number
        {
            return this._value;
        }
        

        public function get startIndex() : int
        {
            return this._startIndex;
        }
        

        public function get endIndex() : int
        {
            return this._endIndex;
        }
        
    }
}