// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/GradientType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{
    
    
    public final class GradientType
    {
        // Value used to specify a linear gradient fill.
        public static const LINEAR:String = "linear";
        
        // Value used to specify a radial gradient fill.
        public static const RADIAL:String = "radial";
        
        
    }
}