// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/InterpolationMethod.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{
    
    
    public final class InterpolationMethod
    {
        // Specifies that the linear RGB interpolation method should be used.
        public static const LINEAR_RGB:String = "linearRGB";
        
        // Specifies that the RGB interpolation method should be used.
        public static const RGB:String = "rgb";
        
        
    }
}