// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/PixelSnapping.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{

    public final class PixelSnapping
    {
        // A constant value used in the pixelSnapping property of a Bitmap object to specify that the bitmap image is always snapped to the nearest pixel, independent of any transformation.
        public static const ALWAYS:String = "always";

        // A constant value used in the pixelSnapping property of a Bitmap object to specify that the bitmap image is snapped to the nearest pixel if it is drawn with no rotation or skew 
        // and it is drawn at a scale factor of 99.9% to 100.1%.
        public static const AUTO:String = "auto";

        // A constant value used in the pixelSnapping property of a Bitmap object to specify that no pixel snapping occurs.
        public static const NEVER:String = "never";

    }
}
