// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ShaderPrecision.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{

    public final class ShaderPrecision
    {
        // Represents fast precision mode.
        public static const FAST:String = "fast";

        // Represents full precision mode.
        public static const FULL:String = "full";

    }
}