// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ShaderParameterType.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{

    public final class ShaderParameterType
    {
        // Indicates that the shader parameter is defined as a bool value, equivalent to a single Boolean instance in ActionScript.
        public static const BOOL:String = "bool";

        // Indicates that the shader parameter is defined as a bool2 value, equivalent to an Array of two Boolean instances in ActionScript.
        public static const BOOL2:String = "bool2";

        // Indicates that the shader parameter is defined as a bool3 value, equivalent to an Array of three Boolean instances in ActionScript.
        public static const BOOL3:String = "bool3";

        // Indicates that the shader parameter is defined as a bool4 value, equivalent to an Array of four Boolean instances in ActionScript.
        public static const BOOL4:String = "bool4";

        // Indicates that the shader parameter is defined as a float value, equivalent to a single Number instance in ActionScript.
        public static const FLOAT:String = "float";

        // Indicates that the shader parameter is defined as a float2 value, equivalent to an Array of two Number instances in ActionScript.
        public static const FLOAT2:String = "float2";

        // Indicates that the shader parameter is defined as a float3 value, equivalent to an Array of three Number instances in ActionScript.
        public static const FLOAT3:String = "float3";

        // Indicates that the shader parameter is defined as a float4 value, equivalent to an Array of four Number instances in ActionScript.
        public static const FLOAT4:String = "float4";

        // Indicates that the shader parameter is defined as an int value, equivalent to a single int or uint instance in ActionScript.
        public static const INT:String = "int";

        // Indicates that the shader parameter is defined as an int2 value, equivalent to an Array of two int or uint instances in ActionScript.
        public static const INT2:String = "int2";

        // Indicates that the shader parameter is defined as an int3 value, equivalent to an Array of three int or uint instances in ActionScript.
        public static const INT3:String = "int3";

        // Indicates that the shader parameter is defined as an int4 value, equivalent to an Array of four int or uint instances in ActionScript.
        public static const INT4:String = "int4";

        // Indicates that the shader parameter is defined as a float2x2 value, equivalent to a 2-by-2 matrix.
        public static const MATRIX2X2:String = "matrix2x2";

        // Indicates that the shader parameter is defined as a float3x3 value, equivalent to a 3-by-3 matrix.
        public static const MATRIX3X3:String = "matrix3x3";

        // Indicates that the shader parameter is defined as a float4x4 value, equivalent to a 4-by-4 matrix.
        public static const MATRIX4X4:String = "matrix4x4";

    }
}
