// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/ActionScriptVersion.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{

    public final class ActionScriptVersion
    {
        // ActionScript language version 2.0 and earlier.
        public static const ACTIONSCRIPT2:uint = 2;

        // ActionScript language version 3.0.
        public static const ACTIONSCRIPT3:uint = 3;

    }
}