// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/display/SpreadMethod.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.display
{
    
    
    public final class SpreadMethod
    {
        // Specifies that the gradient use the pad spread method.
        public static const PAD:String = "pad";
        
        // Specifies that the gradient use the reflect spread method.
        public static const REFLECT:String = "reflect";
        
        // Specifies that the gradient use the repeat spread method.
        public static const REPEAT:String = "repeat";
        
        
    }
}