// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/SharedObjectFlushStatus.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{
    
    
    public final class SharedObjectFlushStatus
    {
        // Indicates that the flush completed successfully.
        public static const FLUSHED:String = "flushed";
        
        // Indicates that the user is being prompted to increase disk space for the shared object before the flush can occur.
        public static const PENDING:String = "pending";
        
        
    }
}