// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/URLLoaderDataFormat.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class URLLoaderDataFormat
    {
        // Specifies that downloaded data is received as raw binary data.
        public static const BINARY:String = "binary";

        // Specifies that downloaded data is received as text.
        public static const TEXT:String = "text";

        // Specifies that downloaded data is received as URL-encoded variables.
        public static const VARIABLES:String = "variables";

    }
}
