// The initial version of this file was autogenerated from the official AS3 reference at
// https://help.adobe.com/en_US/FlashPlatform/reference/actionscript/3/flash/net/URLRequestMethod.html
// by https://github.com/golfinq/ActionScript_Event_Builder
// It won't be regenerated in the future, so feel free to edit and/or fix

package flash.net
{

    public final class URLRequestMethod
    {
        // Specifies that the URLRequest object is a GET.
        public static const GET:String = "GET";

        // Specifies that the URLRequest object is a POST.
        public static const POST:String = "POST";

    }
}
